
 /**
  * This template file was generated by Dynatrace client.
  * The Dynatrace community portal can be found here: http://community.dynatrace.com/
  * For information how to publish a plugin please visit https://community.dynatrace.com/community/display/DL/How+to+add+a+new+plugin/
  **/ 

package com.realdolmen.dynatrace.restmonitor;

import com.dynatrace.diagnostics.global.Constants;
import com.dynatrace.diagnostics.httpclient.api.DynaTraceHttpClient;
import com.dynatrace.diagnostics.httpclient.api.DynaTraceHttpClientBuilder;
import com.dynatrace.diagnostics.httpclient.api.DynaTraceHttpClientException;
import com.dynatrace.diagnostics.httpclient.api.enums.AuthMode;
import com.dynatrace.diagnostics.httpclient.api.enums.ContentTypeAndEncoding;
import com.dynatrace.diagnostics.httpclient.api.enums.RequestType;
import com.dynatrace.diagnostics.httpclient.api.enums.SSLCertificateMode;
import com.dynatrace.diagnostics.httpclient.api.enums.SSLHostnameVerification;
import com.dynatrace.diagnostics.httpclient.impl.CloseableDynaTraceHttpResponse;
import com.dynatrace.diagnostics.pdk.*;


import java.io.IOException;
import java.io.InputStream;
import java.net.Authenticator;
import java.net.SocketTimeoutException;
import java.net.URL;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;;

import javax.net.ssl.SSLException;

import org.apache.http.Header;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.conn.ConnectTimeoutException;
import org.apache.http.util.EncodingUtils;


import org.apache.http.client.methods.HttpPost;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.conn.ssl.NoopHostnameVerifier;
import org.apache.http.entity.StringEntity;

import org.apache.http.impl.client.*;

/**
 * TODO: documentation
 * 
 * @author heydenb
 *
 * extended code written by hao-lin.liang@dynatrace.com
 */
public class RestMonitor implements Monitor {

	private static final Logger log = Logger.getLogger(RestMonitor.class.getName());

	private static final int READ_CHUNK_SIZE = 1024;
	private static final String HTTP_1_0 = "1.0";
	private static final int HTTP_CODE_MOVED_PERMANENT = 301;

	private Config config;
	private DynaTraceHttpClient httpClient;
	private DynaTraceHttpClient  postClient;
	private DynaTraceHttpClient getClient;


	private static String cookie;
	private static String token;

	////////

	@Override
	public Status setup(MonitorEnvironment env) throws Exception {
		Status status = new Status(Status.StatusCode.Success);
		try {
			config = new Config(env);
		} catch (Exception ex) {
			log.log(Level.FINE, "setup configuration failed", ex);
			status.setStatusCode(Status.StatusCode.ErrorInternal);
			status.setMessage("Setting up configuration failed: " + ex.getMessage() + "\nType: " + ex.getClass().getSimpleName() +
					"\n");
			status.setShortMessage("Setting up configuration failed: " + ex.getMessage());
			status.setException(ex);
			return status;
		}

		try {
			setupHttpClient();

		} catch (Exception ex) {
			log.log(Level.FINE, "setup http client failed", ex);
			status.setStatusCode(Status.StatusCode.ErrorInternal);
			status.setMessage("Setting up HTTP client failed: " + ex.getMessage() + "\nType: " + ex.getClass().getSimpleName() +
					"\n");
			status.setShortMessage("Setting up HTTP client failed: " + ex.getMessage());
			status.setException(ex);
			return status;
		}

		try {
			setupAuth(httpClient);
		} catch (Exception ex) {
			log.log(Level.FINE, "setup http authentication failed", ex);
			status.setStatusCode(Status.StatusCode.ErrorInternal);
			status.setMessage("Setting up HTTP authentication failed: " + ex.getMessage() + "\nType: " +
					ex.getClass().getSimpleName() + "\n");
			status.setShortMessage("HTTP authentication setup failed: " + ex.getMessage());
			status.setException(ex);
			return status;
		}

		try {
			setupProxy(httpClient);
		} catch (Exception ex) {
			log.log(Level.FINE, "setup proxy failed", ex);
			status.setStatusCode(Status.StatusCode.ErrorInternal);
			status.setMessage("Settingproxy failed: " + ex.getMessage() + "\n");
			status.setShortMessage("Proxy setup failed: " + ex.getMessage());
			status.setException(ex);
			return status;
		}

		return status;
	}

	@Override
	public void teardown(MonitorEnvironment env) throws Exception {
		if (httpClient == null)
			return;
		httpClient.close();
		httpClient = null;
	}

	@Override
	public Status execute(MonitorEnvironment env) throws Exception {

		// cleans up the http client - extended code
		cleanUp();
		setupHttpClient();
		setupAuth(httpClient);

		// propagate log level for execution, so no collector restart is needed
		Logger.getLogger("org.apache.http.wire").setLevel(log.getLevel());

		/////////

		// Sending a post to login - extended code

		log.info("Logging in");
		Config test = new Config();
		test.method = RequestType.POST;
		CloseableDynaTraceHttpResponse response1 = null;

		httpClient.addRequestHeader("Accept","application/json, text/javascript, */*; q=0.01");
		httpClient.addRequestHeader("Content-Type","application/json; charset=UTF-8");

		String payLoadLogin = "{\n"
				+ "  \"email\":\"" +config.serverUsername+ "\",\n"
				+ "  \"password\":\"" +config.serverPassword+"\"\n"
				+ "}";

		String postAddress = config.akanaLoginURI.replaceFirst("/"," ");

		response1 = httpClient.executeBigRequest(test.method,new URL(postAddress),null,payLoadLogin,ContentTypeAndEncoding.TEXT_PLAIN_UTF8);

		log.info(response1.getStatusCode() + "  login status code");
		testResponse(response1);

		////////

		final Status status = new Status();
		final MeasureConnection measureConnection = new MeasureConnection(env);

		final StringBuilder messageBuffer = new StringBuilder("URL: ");
		messageBuffer.append(config.url).append("\n");

		// set dynaTrace tagging header (only timer name)
		if (config.tagging) {
			httpClient.addRequestHeader(Constants.HEADER_DYNATRACE, "NA=" + config.timerName);
		}

		CloseableDynaTraceHttpResponse response = null;
		try {
			log.info("Executing method: " + config.method + ", URI: " + config.url + ", with PostData: " +
					(config.postData != null));

			// connect
			measureConnection.startMeasurement();
			if (config.method == RequestType.POST && config.postData != null) {
				response = httpClient.executeBigRequest(config.method, config.url, null, config.postData,
						ContentTypeAndEncoding.TEXT_PLAIN_UTF8);
			} else {

				response = httpClient.executeBigRequest(config.method, config.url, null);
			}
			
			if (response.getStatusCode() == HTTP_CODE_MOVED_PERMANENT)
				throw new DynaTraceHttpClientException(new ClientProtocolException(
						"301 redirect reached, not supported for the REST Monitor."));

			measureConnection.headerResponseReceived();
			measureConnection.setHttpStatusCode(response.getStatusCode());
			measureConnection.setHeaderSize(calculateHeaderSize(response));
			log.info("http request succeed. code=" + response.getStatusCode());

			// read response data (only if more than the header was requested)
			if (config.method != RequestType.HEAD) {
				try {
					log.fine("start loading result content");
					StringBuilder resultContent = loadResultContent(response, measureConnection);
					log.info(resultContent.toString() + " first part of result content");
					log.fine("result content loaded ... ");
					if (resultContent!=null){
						if (log.isLoggable(Level.FINE)){
							messageBuffer.append("content: \n" + resultContent.toString());
						}
						final MeasureCapturedValues measureCapturedValues = new MeasureCapturedValues(env);
						measureCapturedValues.applyMeasuresToEnvironment(resultContent.toString(), config.format);
						log.info(resultContent.toString() + "  this is the result content");
					}
				} catch (IOException e) {
					log.log(Level.FINE, "reading content failed", e);
					status.setException(e);
					status.setStatusCode(Status.StatusCode.PartialSuccess);
					status.setShortMessage("reading content failed: " + e.getMessage());
					messageBuffer.append("Error while loading content: ").append(e.getClass().getSimpleName()).append(": ").append(
							e.getMessage()).append("\n");
				} catch (RestMonitorConfigurationException e) {

					log.log(Level.FINE, "configuration fault", e);
					status.setException(e);
					status.setStatusCode(Status.StatusCode.ErrorInternalConfigurationProblem);
					status.setShortMessage(e.getMessage());
					messageBuffer.append("Error capturing measures: ").append(e.getClass().getSimpleName()).append(": ").append(
							e.getMessage()).append("\n");
				} catch (Exception e) {
					log.log(Level.FINE, "configuration fault", e);
					status.setException(e);
					status.setStatusCode(Status.StatusCode.ErrorInternal);
					status.setShortMessage(e.getMessage());
					messageBuffer.append("Error internal: ").append(e.getClass().getSimpleName()).append(": ").append(
						e.getMessage()).append("\n");
				}
			} else {
				measureConnection.loadResponseContentFinished();
			}
			measureConnection.startClosing();
		} catch (DynaTraceHttpClientException e) {
			//log.log(Level.FINE, "executing request failed", e);
			status.setException(e);
			status.setStatusCode(Status.StatusCode.PartialSuccess);
			messageBuffer.append("Connection failed: ").append(e.getClass().getSimpleName()).append(": ").append(
					e.getMessage()).append("\n");
			if (e.getCause() != null) {
				messageBuffer.append("Caused by: ").append(e.getCause().getClass().getSimpleName()).append(": ").append(
						e.getCause().getMessage()).append("\n");
				status.setShortMessage(e.getCause().getClass().getSimpleName() + ": " + e.getCause().getMessage());
				if (e.getCause() instanceof SSLException) {
					messageBuffer.append("SSL handshake failed, this may be caused by an incorrect certificate. Check 'Disable certificate validation' parameter to override this.\n");
				} else if (e.getCause() instanceof ConnectTimeoutException) {
					measureConnection.setConnectionTimedOut();
				} else if (e.getCause() instanceof SocketTimeoutException) {
					measureConnection.setSocketTimedOut();
				}
			} else {
				status.setShortMessage(e.getClass().getSimpleName() + ": " + e.getMessage());
			}
		} catch (Exception e){
			log.log(Level.SEVERE, "unknown error", e);
			status.setException(e);
			status.setStatusCode(Status.StatusCode.ErrorInternal);
			messageBuffer.append("Caused by: ").append(e.getClass().getSimpleName()).append(": ").append(
					e.getMessage()).append("\n");
			e.fillInStackTrace();
			for (StackTraceElement el : e.getStackTrace()){
				messageBuffer.append(el.toString()).append("\n");
			}
		}
		finally {
			// always release the connection
			if (response != null)
				response.close();
			measureConnection.closingFinished();
		}
		
		log.info("parsed!");

		measureConnection.applyBinaryMeasuresToEnvironment();
		if (status.getStatusCode() == Status.StatusCode.Success)
			log.info("second call of applyMeasures");
			measureConnection.applyMeasuresToEnvironment();

		status.setMessage(messageBuffer.toString());

		/// logout here - extended code

		log.info("Loging out");
		Config test1 = new Config();
		test1.method = RequestType.GET;
		CloseableDynaTraceHttpResponse response2 = null;

		String logoutAddress = "https://staging.developer.kingfisher.com/api/login/endsession";
		log.info(test1.method.toString());
		response2 = httpClient.executeBigRequest(test1.method,new URL(logoutAddress),null);

		log.info(response2.getStatusCode() + "  logout status code");


		cleanUp();
		return status;
	}

	/**
	 * loads the whole content out of the http response.
	 *
	 * @return null if there was no content in the http response OR config parameter contentMatch is disabled OR contentMatch is
	 *         bytesMatch.
	 */
	private StringBuilder loadResultContent(CloseableDynaTraceHttpResponse response, MeasureConnection measureCollector) throws IOException {
		InputStream inputStream = response.getResponseBody();
		if (inputStream == null) {
			return null;
		}
		int bytesRead;
		byte[] data = new byte[READ_CHUNK_SIZE];
		String charset = response.getCharset();
		StringBuilder buf = new StringBuilder();
		while ((bytesRead = inputStream.read(data)) > 0) {
			buf.append(EncodingUtils.getString(data, 0, bytesRead, charset));
			measureCollector.incrementInputSize(bytesRead);
		}
		inputStream.close();
		log.info("response for get i think   " + buf.toString());
		measureCollector.loadResponseContentFinished();
		return buf;
	}
	//////////
	////////////
	////////

	private void setupAuth(DynaTraceHttpClient httpClient) throws IllegalStateException, UnknownHostException {
		// change this so it doesnt do anything, dont need the httpclient to connect once it has the cookie and token
		if (config.serverAuth == AuthMethod.basic) {
			log.info("setting up basic authentication");
		// extended - commented out

//			httpClient.setUserCredentials(config.serverUsername, config.serverPassword);
//			httpClient.setPreemptiveAuthEnabled(config.serverAuthPreemptive);
//			if (config.serverAuthPreemptive) {
//				httpClient.setPreemptiveAuthMode(AuthMode.BASIC);

//			}
		}
		else if (config.serverAuth == AuthMethod.NTLM) {
			String user = config.serverUsername;
			String domain = "";
			if (config.serverUsername != null) {
				int idx = config.serverUsername.indexOf("\\");
				if (idx > 0) {
					user = config.serverUsername.substring(idx + 1);
					domain = config.serverUsername.substring(0, idx);
				}
			}
			httpClient.setNTLMUserCredentials(config.url.getHost(), config.url.getPort(), user, config.serverPassword, domain,
					java.net.InetAddress.getLocalHost().getHostName());
		}
		log.info("finished setupAuth");
	}

	private void setupProxy(DynaTraceHttpClient httpClient) {
		if (!config.useProxy) {
			return;
		}
		if (config.proxyAuth) {
			httpClient.setProxy(config.proxyHost, config.proxyPort, config.proxyUsername, config.proxyPassword,
					config.proxyAuthPreemptive);
		} else {
			httpClient.setProxy(config.proxyHost, config.proxyPort);
		}
	}

	// modified
	private void setupHttpClient() {
		DynaTraceHttpClientBuilder builder = new DynaTraceHttpClientBuilder();
		if (config.ignorecert) {
			builder.certificateMode(SSLCertificateMode.TRUST_ALL);
			builder.hostnameVerificationMode(SSLHostnameVerification.ALLOW_ALL);
		} else {
			builder.certificateMode(SSLCertificateMode.VERIFY_CHAIN);
			builder.hostnameVerificationMode(SSLHostnameVerification.DEFAULT);
		}

		if (HTTP_1_0.equals(config.httpVersion)) {
			builder.protocolVersion("HTTP", 1, 0);
		} else {
			builder.protocolVersion("HTTP", 1, 1);
		}

		builder.allowRedirects(false).maxRedirects(0);
		builder.userAgent(config.userAgent);
		builder.socketTimeout(config.socketTimeout);
		builder.connectTimeout(config.connectionTimeout);
		builder.connectionRequestTimeout(config.connectionTimeout);
		httpClient = builder.build();
		postClient = builder.build();
		getClient = builder.build();

	//	return httpClient;
	}

	private int calculateHeaderSize(CloseableDynaTraceHttpResponse response) {
		int headerLength = 0;
		for (Header header : response.getResponseHeaders()) {
			headerLength += header.getName().getBytes().length;
			headerLength += header.getValue().getBytes().length;
		}
		return headerLength;
	}


	//extended code

	private void cleanUp(){
		if (httpClient == null)
			return;
		httpClient.close();
		httpClient = null;
	}

	private void testResponse(CloseableDynaTraceHttpResponse response) throws IOException{

		InputStream inputStream = response.getResponseBody();

		int bytesRead;
		byte[] data = new byte[READ_CHUNK_SIZE];
		String charset = response.getCharset();
		StringBuilder buf = new StringBuilder();
		while ((bytesRead = inputStream.read(data)) > 0) {
			buf.append(EncodingUtils.getString(data, 0, bytesRead, charset));

		}
		log.info(buf.toString());
	}

	private String[] cookieTransformation(Header cookie, Header token){
		String cookieVal = cookie.getValue().split(";path")[0];
		String tokenVal = token.getValue().split(";path")[0];

		String [] cookieToken = new String[2];
		cookieToken[0]=cookieVal;
		cookieToken[1]=tokenVal;
		log.info("cookie transformation " + cookieVal+"  tokenvalue  " + tokenVal );
		return cookieToken;
	}
}
